### ISSUE TITLE
Est-il possible d'ajouter des tags plus précis pour JOSM ? En se basant sur le contenu du fichier merimee ?

### ISSUE THREAD

**Issue by sidjy** [JeaRRo/Wom#1]
Bonjour,

en fait, j'ai fait un petit script qui permet de rajouter des tags plus précis en fonction de la description du monument inscrit ou classé...

Celà donne ceci : 
```
[PA00078022][menhir dit la pierre-au-coq|][]historic=archaeological_site|site_type=megalith|megalith_type=menhir
[PA00078023][église saint-denis][12e siècle ; 16e siècle]start_date=12C|amenity=place_of_worship|religion=christian|building=church
[PA00078024][église saint-phal d avirey][16e siècle ; 19e siècle]start_date=16C|amenity=place_of_worship|religion=christian|building=church
[PA00078025][église][15e siècle ; 16e siècle]start_date=15C|amenity=place_of_worship|religion=christian|building=church
[PA00078026][église][16e siècle]start_date=16C|amenity=place_of_worship|religion=christian|building=church
[PA00078027][église saint-pierre-et-saint-paul][12e siècle ; 16e siècle]start_date=12C|amenity=place_of_worship|religion=christian|building=church
[PA00078028][presbytère  ancien ][4e quart 18e siècle]start_date=18C|religion=catholic
[PA00078029][couvent des ursulines  ancien ][17e siècle ; 1er quart 19e siècle]start_date=17C|historic=monastery|monastery:type=convent
[PA00078030][église saint-maclou][12e siècle ; 13e siècle ; 14e siècle ; 18e siècle]start_date=12C|amenity=place_of_worship|religion=christian|building=church
```

Evidemment, il y a parfois quelques erreurs (si dans la description, il est indiqué "croix à côté de l'église", les tags d'une croix ET de l'église seront positionnés par exemple, mais je pense que c'est une aide utile à l'intégration des monuments ?!

Ah oui, vu que je ne connais pas python mais uniquement perl, le script est en perl, désolé.

[merimee.zip](https://github.com/JeaRRo/Wom/files/640303/merimee.zip)

**Comment by JeaRRo** [comment]
Salut
merci pour cette proposition. C'est une idée intéressante que je vais essayer d'intégrer.

**Comment by JeaRRo** [comment]
Fonctionnalité ajoutée le 12/12/2016

**Comment by sidjy** [comment]
Super, les tags sont bien affichés mais "Créer un point dans JOSM" ne les rajoute pas ?!

**Comment by JeaRRo** [comment]
salut
"Créer un point dans JOSM" intègre désormais les tags standards... visibles à partir de demain matin
merci pour l'alerte
A+
